(in-package #:opendaq)

(defconstant +daq-success+ #x00000000)

;; --- Error code constants ---------------------------------------------------
(defconstant +daq-err-nomemory+                    #x80000000)
(defconstant +daq-err-invalid-parameter+           #x80000001)
(defconstant +daq-err-nointerface+                 #x80004002)
(defconstant +daq-err-size-too-small+              #x80000003)
(defconstant +daq-err-conversion-failed+           #x80000004)
(defconstant +daq-err-out-of-range+                #x80000005)
(defconstant +daq-err-not-found+                   #x80000006)
(defconstant +daq-err-already-exists+              #x8000000A)
(defconstant +daq-err-not-assigned+                #x8000000B)
(defconstant +daq-err-call-failed+                 #x8000000C)
(defconstant +daq-err-parse-failed+                #x8000000D)
(defconstant +daq-err-invalid-value+               #x8000000E)
(defconstant +daq-err-resolve-failed+              #x80000010)
(defconstant +daq-err-invalid-type+                #x80000011)
(defconstant +daq-err-access-denied+               #x80000012)
(defconstant +daq-err-not-enabled+                 #x80000013)
(defconstant +daq-err-general-error+               #x80000014)
(defconstant +daq-err-calc-failed+                 #x80000015)
(defconstant +daq-err-not-implemented+             #x80000016)
(defconstant +daq-err-frozen+                      #x80000017)
(defconstant +daq-err-not-serializable+            #x80000018)
(defconstant +daq-err-factory-not-registered+      #x80000020)
(defconstant +daq-err-deserialize-parse-error+     #x80000021)
(defconstant +daq-err-deserialize-unknown-type+    #x80000022)
(defconstant +daq-err-deserialize-no-type+         #x80000023)
(defconstant +daq-err-invalid-property+            #x80000024)
(defconstant +daq-err-duplicate-item+              #x80000025)
(defconstant +daq-err-argument-null+               #x80000026)
(defconstant +daq-err-invalid-operation+           #x80000027)
(defconstant +daq-err-uninitialized+               #x80000028)
(defconstant +daq-err-invalid-state+               #x80000029)
(defconstant +daq-err-validate-failed+             #x80000030)
(defconstant +daq-err-not-updatable+               #x80000031)
(defconstant +daq-err-no-compatible-version+       #x80000032)
(defconstant +daq-err-locked+                      #x80000033)
(defconstant +daq-err-size-too-large+              #x80000034)
(defconstant +daq-err-buffer-full+                 #x80000035)
(defconstant +daq-err-create-failed+               #x80000036)
(defconstant +daq-err-empty-scaling-table+         #x80000037)
(defconstant +daq-err-empty-range+                 #x80000038)
(defconstant +daq-err-discovery-failed+            #x80000039)
(defconstant +daq-err-coerce-failed+               #x80000040)
(defconstant +daq-err-not-supported+               #x80000041)
(defconstant +daq-err-list-not-homogeneous+        #x80000042)
(defconstant +daq-err-not-frozen+                  #x80000043)
(defconstant +daq-err-no-data+                     #x80000050)
(defconstant +daq-err-device-locked+               #x80000052)
(defconstant +daq-err-reserved-type-name+          #x80000053)

(defparameter *known-error-codes*
  `((,+daq-success+                     . "OPENDAQ_SUCCESS")
    (,+daq-err-nomemory+                . "OPENDAQ_ERR_NOMEMORY")
    (,+daq-err-invalid-parameter+       . "OPENDAQ_ERR_INVALIDPARAMETER")
    (,+daq-err-nointerface+             . "OPENDAQ_ERR_NOINTERFACE")
    (,+daq-err-size-too-small+          . "OPENDAQ_ERR_SIZETOOSMALL")
    (,+daq-err-conversion-failed+       . "OPENDAQ_ERR_CONVERSIONFAILED")
    (,+daq-err-out-of-range+            . "OPENDAQ_ERR_OUTOFRANGE")
    (,+daq-err-not-found+               . "OPENDAQ_ERR_NOTFOUND")
    (,+daq-err-already-exists+          . "OPENDAQ_ERR_ALREADYEXISTS")
    (,+daq-err-not-assigned+            . "OPENDAQ_ERR_NOTASSIGNED")
    (,+daq-err-call-failed+             . "OPENDAQ_ERR_CALLFAILED")
    (,+daq-err-parse-failed+            . "OPENDAQ_ERR_PARSEFAILED")
    (,+daq-err-invalid-value+           . "OPENDAQ_ERR_INVALIDVALUE")
    (,+daq-err-resolve-failed+          . "OPENDAQ_ERR_RESOLVEFAILED")
    (,+daq-err-invalid-type+            . "OPENDAQ_ERR_INVALIDTYPE")
    (,+daq-err-access-denied+           . "OPENDAQ_ERR_ACCESSDENIED")
    (,+daq-err-not-enabled+             . "OPENDAQ_ERR_NOTENABLED")
    (,+daq-err-general-error+           . "OPENDAQ_ERR_GENERALERROR")
    (,+daq-err-calc-failed+             . "OPENDAQ_ERR_CALCFAILED")
    (,+daq-err-not-implemented+         . "OPENDAQ_ERR_NOTIMPLEMENTED")
    (,+daq-err-frozen+                  . "OPENDAQ_ERR_FROZEN")
    (,+daq-err-not-serializable+        . "OPENDAQ_ERR_NOT_SERIALIZABLE")
    (,+daq-err-factory-not-registered+  . "OPENDAQ_ERR_FACTORY_NOT_REGISTERED")
    (,+daq-err-deserialize-parse-error+ . "OPENDAQ_ERR_DESERIALIZE_PARSE_ERROR")
    (,+daq-err-deserialize-unknown-type+ . "OPENDAQ_ERR_DESERIALIZE_UNKNOWN_TYPE")
    (,+daq-err-deserialize-no-type+     . "OPENDAQ_ERR_DESERIALIZE_NO_TYPE")
    (,+daq-err-invalid-property+        . "OPENDAQ_ERR_INVALIDPROPERTY")
    (,+daq-err-duplicate-item+          . "OPENDAQ_ERR_DUPLICATEITEM")
    (,+daq-err-argument-null+           . "OPENDAQ_ERR_ARGUMENT_NULL")
    (,+daq-err-invalid-operation+       . "OPENDAQ_ERR_INVALID_OPERATION")
    (,+daq-err-uninitialized+           . "OPENDAQ_ERR_UNINITIALIZED")
    (,+daq-err-invalid-state+           . "OPENDAQ_ERR_INVALIDSTATE")
    (,+daq-err-validate-failed+         . "OPENDAQ_ERR_VALIDATE_FAILED")
    (,+daq-err-not-updatable+           . "OPENDAQ_ERR_NOT_UPDATABLE")
    (,+daq-err-no-compatible-version+   . "OPENDAQ_ERR_NO_COMPATIBLE_VERSION")
    (,+daq-err-locked+                  . "OPENDAQ_ERR_LOCKED")
    (,+daq-err-size-too-large+          . "OPENDAQ_ERR_SIZETOOLARGE")
    (,+daq-err-buffer-full+             . "OPENDAQ_ERR_BUFFERFULL")
    (,+daq-err-create-failed+           . "OPENDAQ_ERR_CREATE_FAILED")
    (,+daq-err-empty-scaling-table+     . "OPENDAQ_ERR_EMPTY_SCALING_TABLE")
    (,+daq-err-empty-range+             . "OPENDAQ_ERR_EMPTY_RANGE")
    (,+daq-err-discovery-failed+        . "OPENDAQ_ERR_DISCOVERY_FAILED")
    (,+daq-err-coerce-failed+           . "OPENDAQ_ERR_COERCE_FAILED")
    (,+daq-err-not-supported+           . "OPENDAQ_ERR_NOT_SUPPORTED")
    (,+daq-err-list-not-homogeneous+    . "OPENDAQ_ERR_LIST_NOT_HOMOGENEOUS")
    (,+daq-err-not-frozen+              . "OPENDAQ_ERR_NOT_FROZEN")
    (,+daq-err-no-data+                 . "OPENDAQ_ERR_NO_DATA")
    (,+daq-err-device-locked+           . "OPENDAQ_ERR_DEVICE_LOCKED")
    (,+daq-err-reserved-type-name+      . "OPENDAQ_ERR_RESERVED_TYPE_NAME")))

;; --- FFI binding for retrieving the descriptive error message ---------------
(cffi:defcfun ("daqGetErrorInfoMessage" %daq-get-error-info-message) daq-err-code
  (error-message (:pointer daq-string)))

(defun %get-error-message (code)
  "Retrieve the human-readable error message from the openDAQ library.
Returns NIL if no error information is available.
Uses direct FFI calls to avoid re-entering %check-error during error reporting."
  (declare (ignore code))
  (cffi:with-foreign-object (message-slot 'daq-string)
    (let ((stored-code (%daq-get-error-info-message message-slot)))
      (when (%failure-code-p stored-code)
        (let ((msg-ptr (cffi:mem-ref message-slot 'daq-string)))
          (unless (cffi:null-pointer-p msg-ptr)
            (unwind-protect
                 (cffi:with-foreign-object (char-ptr-slot 'daq-const-char-ptr)
                   (let ((err (%daq-string-get-char-ptr msg-ptr char-ptr-slot)))
                     (if (%failure-code-p err)
                         nil
                         (let ((c-str (cffi:mem-ref char-ptr-slot 'daq-const-char-ptr)))
                           (if (cffi:null-pointer-p c-str)
                               nil
                               (cffi:foreign-string-to-lisp c-str))))))
              (base-object/release-ref msg-ptr))))))))

;; --- Condition and checking -------------------------------------------------

(define-condition opendaq-error (error)
  ((code :initarg :code :reader opendaq-error-code)
   (operation :initarg :operation :reader opendaq-error-operation)
   (message :initarg :message :reader opendaq-error-message :initform nil))
  (:report
   (lambda (condition stream)
     (let* ((code (opendaq-error-code condition))
            (name (cdr (assoc code *known-error-codes*)))
            (detail (opendaq-error-message condition)))
       (format stream
               "openDAQ call ~A failed with ~A (~8,'0X).~@[ ~A~]"
               (opendaq-error-operation condition)
               (or name "an unknown error")
               code
               detail)))))

(defun %failure-code-p (code)
  (not (zerop (logand code #x80000000))))

(defun %check-error (code operation)
  (when (%failure-code-p code)
    (error 'opendaq-error
           :code code
           :operation operation
           :message (%get-error-message code)))
  code)
