(in-package #:opendaq.tests)

(in-suite high-level-coretypes-suite)

(defparameter *high-level-coretypes-event-called* nil)

(cffi:defcallback %high-level-coretypes-on-event :void ((sender daq.ll::daq-base-object)
                                                        (args daq.ll::daq-base-object))
  (setf *high-level-coretypes-event-called* t)
  (daq.ll:base-object/release-ref sender)
  (daq.ll:base-object/release-ref args))

(test high-level-coretypes-primitives
  (let* ((base-object (daq:wrap-base-object (daq.ll:base-object/create)))
         (wrapped-ratio (daq:wrap-ratio (daq.ll:ratio/create-ratio 8 12)))
         (ratio (make-instance 'daq:ratio :numerator 6 :denominator 9))
         (simplified (daq:simplify ratio))
         (boolean (make-instance 'daq:daq-boolean :value nil))
         (complex-number (make-instance 'daq:complex-number :real 1.0d0 :imaginary 2.0d0))
         (integer (make-instance 'daq:daq-integer :value 1))
         (float-object (make-instance 'daq:float-object :value 1.0d0))
         (string-object (daq:wrap-daq-string-object (daq.ll:make-daq-string "test")))
         (simple-type (make-instance 'daq:simple-type :core-type :daq-ct-int))
         (version-info (make-instance 'daq:version-info :major 1 :minor 2 :patch 3))
         (binary-data (make-instance 'daq:binary-data :size 16)))
    (is (typep base-object 'daq:base-object)
        "High-level wrappers should be able to adopt low-level base-object pointers.")
    (is (= 8 (daq:numerator wrapped-ratio))
        "Low-level ratio pointers should be consumable through the generated high-level namespace alias.")
    (is (= 12 (daq:denominator wrapped-ratio))
        "Wrapped low-level ratios should preserve their denominator.")
    (is (= 6 (daq:numerator ratio))
        "High-level ratios should preserve their numerator.")
    (is (= 9 (daq:denominator ratio))
        "High-level ratios should preserve their denominator.")
    (is (= 2 (daq:numerator simplified))
        "High-level ratio simplification should produce the reduced numerator.")
    (is (= 3 (daq:denominator simplified))
        "High-level ratio simplification should produce the reduced denominator.")
    (is (null (daq:value boolean))
        "High-level boolean wrappers should decode false values into NIL.")
    (is (= 1.0d0 (daq:real complex-number))
        "High-level complex numbers should expose their real component.")
    (is (= 2.0d0 (daq:imaginary complex-number))
        "High-level complex numbers should expose their imaginary component.")
    (is (= 1 (daq:value integer))
        "High-level integer wrappers should expose their boxed value.")
    (is (= 1.0d0 (daq:value float-object))
        "High-level float wrappers should expose their boxed value.")
    (is (string= "test" (%boxed-string-value string-object))
        "High-level string wrappers should round-trip the native string.")
    (is (not (cffi:null-pointer-p (daq:raw-pointer simple-type)))
        "High-level simple-type wrappers should create a native type object.")
    (is (= 1 (daq:major version-info))
        "High-level version-info wrappers should expose the major version.")
    (is (= 2 (daq:minor version-info))
        "High-level version-info wrappers should expose the minor version.")
    (is (= 3 (daq:patch version-info))
        "High-level version-info wrappers should expose the patch version.")
    (is (= 16 (daq:size binary-data))
        "High-level binary-data wrappers should preserve their native buffer size.")))

(test high-level-coretypes-collections
  (let ((list (make-instance 'daq:object-list)))
    (daq:push-back list 1)
    (daq:push-back list 2)
    (daq:push-back list 3)
    (is (= 3 (daq:count list))
        "High-level object lists should track the number of boxed elements.")
    (let ((popped (daq:pop-front list)))
      (is (= 1 (%boxed-integer-value popped))
          "High-level object lists should return boxed values from POP-FRONT."))
    (let ((removed (daq:remove-at list 1)))
      (is (= 3 (%boxed-integer-value removed))
          "High-level object lists should return boxed values from REMOVE-AT."))
    (daq:clear list)
    (is (= 0 (daq:count list))
        "High-level object lists should support CLEAR.")
    (let ((dict (make-instance 'daq:dict)))
      (daq:set dict "key" "value")
      (is (= 1 (daq:count dict))
          "High-level dictionaries should track inserted entries.")
      (let ((dict-value (daq:get dict "key")))
        (is (string= "value" (%boxed-string-value dict-value))
            "High-level dictionaries should return boxed string values.")))))

(test high-level-coretypes-enumeration-and-structs
  (let* ((enumerators (make-instance 'daq:dict))
         (field-names (make-instance 'daq:object-list))
         (field-type (make-instance 'daq:simple-type :core-type :daq-ct-int))
         (field-types (make-instance 'daq:object-list))
         (type-manager (make-instance 'daq:type-manager)))
    (daq:set enumerators "One" 1)
    (daq:set enumerators "Two" 2)
    (daq:push-back field-names "int")
    (daq:push-back field-types field-type)
    (let* ((enumeration-type
             (daq:enumeration-type-create-enumeration-type-with-values "MyEnum" enumerators))
           (enumeration (daq:enumeration-create-enumeration-with-type enumeration-type "Two"))
           (struct-type (daq:struct-type-create-struct-type-no-defaults "test" field-names field-types)))
      (daq:add-type type-manager struct-type)
      (let* ((managed-type (daq:type-manager-type type-manager "test"))
             (struct-builder (make-instance 'daq:struct-builder :name "test" :type-manager type-manager)))
        (daq:set struct-builder "int" 10)
        (let* ((struct (daq:build struct-builder))
               (field-value (daq:get struct "int")))
          (is (= 2 (daq:count enumeration-type))
              "High-level enumeration types should report their number of enumerators.")
          (is (= 2 (daq:int-value enumeration))
              "High-level enumeration values should expose their numeric value.")
          (is (daq:has-type type-manager "test")
              "High-level type managers should track added struct types.")
          (is (string= "test" (daq:name managed-type))
              "High-level type managers should resolve added types by name.")
          (is (= 10 (%boxed-integer-value field-value))
              "High-level structs should preserve values assigned through the generated builder.")
          (daq:remove-type type-manager "test")
          (is (not (daq:has-type type-manager "test"))
              "High-level type managers should remove registered types."))))))

(test high-level-coretypes-events
  (let* ((event (make-instance 'daq:event))
         (event-args (make-instance 'daq:event-args :event-id 10 :event-name "test_event"))
         (handler (make-instance 'daq:event-handler :call (cffi:callback %high-level-coretypes-on-event)))
         (sender (daq:wrap-base-object (daq.ll:base-object/create))))
    (setf *high-level-coretypes-event-called* nil)
    (is (= 0 (daq:subscriber-count event))
        "High-level events should start without subscribers.")
    (is (= 10 (daq:event-id event-args))
        "High-level event arguments should expose their numeric event identifier.")
    (is (string= "test_event" (daq:event-name event-args))
        "High-level event arguments should expose their event name.")
    (daq:add-handler event handler)
    (is (= 1 (daq:subscriber-count event))
        "High-level events should register generated event handlers.")
    (daq:handle-event handler sender event-args)
    (is (not (null *high-level-coretypes-event-called*))
        "High-level event handlers should invoke the supplied callback.")))

(defun %probe-ratio-finalization ()
  (eval
   '(let* ((release-state (list nil))
          (weak-pointer
            (let ((ratio (make-instance 'daq:ratio
                                        :numerator 14
                                        :denominator 21
                                        :release-hook (lambda ()
                                                        (setf (car release-state) t)))))
              (trivial-garbage:make-weak-pointer ratio))))
      (loop repeat 200
           until (and (car release-state)
                      (null (trivial-garbage:weak-pointer-value weak-pointer)))
           do (trivial-garbage:gc :full t)
              (sleep 0.05))
      (values (car release-state)
             (null (trivial-garbage:weak-pointer-value weak-pointer))))))

(test high-level-ratio-automatic-release
  (multiple-value-bind (released wrapper-reclaimed-p)
      (%probe-ratio-finalization)
    (is (not (null released))
        "High-level wrappers should release their native pointer when reclaimed by GC.")
    (is (not (null wrapper-reclaimed-p))
        "High-level wrapper objects should themselves remain reclaimable after native cleanup.")))
