(in-package #:opendaq.tests)

(in-suite high-level-smoke-suite)

(test high-level-simulator-reads
  (locally (declare (optimize (debug 3)))
    (let* ((instance (make-instance 'daq:instance))
           (root-device (daq:root-device instance))
           (device (daq:add-device root-device "daqref://device0"))
           (channel (daq:find-component device "IO/AI/RefCh0"))
           (signals (daq:signals-recursive (daq:as channel 'daq:channel))))
      (is (plusp (cl:length signals))
          "High-level signal discovery should find at least one signal on the channel.")
      (let ((signal (first signals)))
        ;; No priming read: the first READ must skip the reader's initial
        ;; descriptor-change event on its own and still return samples.
        (let ((reader (make-instance 'daq:stream-reader :signal signal)))
          (let ((samples (daq:read reader 100 :timeout-ms 2000)))
            (is (vectorp samples)
                "Stream reader READ should return a vector.")
            (is (= 100 (cl:length samples))
                "Stream reader READ should return the requested number of samples.")
            (is (every #'numberp samples)
                "Stream reader READ should return numeric elements.")
            (is (eq 'double-float (array-element-type samples))
                "Stream reader default value-type should be double-float.")))
        (let ((reader2 (make-instance 'daq:stream-reader :signal signal)))
          (multiple-value-bind (values domain)
              (daq:read-with-domain reader2 10 :timeout-ms 2000)
            (is (= 10 (cl:length values))
                "read-with-domain should return the requested number of values.")
            (is (vectorp domain)
                "read-with-domain domain should be a vector.")
            (is (= (cl:length values) (cl:length domain))
                "read-with-domain value and domain arrays must have equal length.")
            (is (equal '(signed-byte 64) (array-element-type domain))
                "read-with-domain domain default type should be signed-byte 64.")
            (let ((timestamps (map 'vector (daq:domain-time-converter signal) domain)))
              (is (= (cl:length domain) (cl:length timestamps))
                  "domain-time-converter should map each tick to a timestamp.")
              (is (every (lambda (ts) (typep ts 'local-time:timestamp)) timestamps)
                  "domain-time-converter should produce LOCAL-TIME timestamps.")
              (is (apply #'local-time:timestamp<= (coerce timestamps 'list))
                  "Successive domain ticks should map to non-decreasing timestamps.")
              (is (local-time:timestamp= (aref timestamps 0)
                                         (daq:domain-tick->timestamp signal (aref domain 0)))
                  "domain-tick->timestamp should agree with the domain-time-converter closure."))))))))

(test high-level-multi-reader
  (locally (declare (optimize (debug 3)))
    (let* ((instance (make-instance 'daq:instance))
           (device (daq:add-device (daq:root-device instance) "daqref://device0"))
           (channels (list (daq:as (daq:find-component device "IO/AI/RefCh0") 'daq:channel)
                           (daq:as (daq:find-component device "IO/AI/RefCh1") 'daq:channel)))
           (signals (mapcar (lambda (channel) (first (daq:signals channel))) channels))
           ;; :SIGNALS accepts a plain Lisp list (built into an object-list for us).
           (reader (make-instance 'daq:multi-reader :signals signals)))
      ;; The first reads only synchronise the streams; loop until aligned data.
      (loop for attempt below 30
            do (multiple-value-bind (values domain)
                   (daq:read-with-domain reader 10 :timeout-ms 1000)
                 (when (plusp (cl:length (first domain)))
                   (is (= 2 (cl:length values))
                       "Multi reader should return one value vector per signal.")
                   (is (= 2 (cl:length domain))
                       "Multi reader should return one domain vector per signal.")
                   (is (apply #'= (mapcar #'cl:length values))
                       "All per-signal value vectors should share the same length.")
                   (is (every (lambda (v) (eq 'double-float (array-element-type v))) values)
                       "Multi reader default value type should be double-float.")
                   (is (equalp (first domain) (second domain))
                       "Synchronised signals should share identical domain ticks.")
                   (is (= 2 (cl:length (daq:read reader 5 :timeout-ms 1000)))
                       "Multi reader READ should also return one vector per signal.")
                   (return)))
            finally (fail "Multi reader did not synchronise within the attempt budget.")))))

(test high-level-block-reader
  (locally (declare (optimize (debug 3)))
    (let* ((instance (make-instance 'daq:instance))
           (root-device (daq:root-device instance))
           (device (daq:add-device root-device "daqref://device0"))
           (channel (daq:find-component device "IO/AI/RefCh0"))
           (signals (daq:signals-recursive (daq:as channel 'daq:channel)))
           (signal (first signals))
           (reader (make-instance 'daq:block-reader :signal signal :block-size 10)))
      (let ((blocks (daq:read reader 5 :timeout-ms 2000)))
        (is (= 2 (array-rank blocks))
            "block reader READ should return a 2-D array.")
        (is (= 5 (array-dimension blocks 0))
            "block reader READ should return the requested number of blocks.")
        (is (= 10 (array-dimension blocks 1))
            "block reader READ columns should equal the block size.")
        (is (eq 'double-float (array-element-type blocks))
            "block reader default value-type should be double-float.")))))

(test high-level-data-packet-buffers
  (let ((builder (make-instance 'daq:data-descriptor-builder)))
    (setf (daq:sample-type builder) opendaq.low-level::+daq-sample-type-float-64+)
    (let* ((descriptor (daq:build builder))
           (offset (make-instance 'daq:daq-integer :value 0))
           (packet (make-instance 'daq:data-packet
                                  :descriptor descriptor :sample-count 8 :offset offset))
           (values (daq:data packet))
           (raw (daq:raw-data packet)))
      (is (vectorp values)
          "data-packet DATA should return a vector.")
      (is (= 8 (cl:length values))
          "data-packet DATA length should match the sample count.")
      (is (eq 'double-float (array-element-type values))
          "data-packet DATA element type should follow the descriptor sample type.")
      (is (equal '(unsigned-byte 8) (array-element-type raw))
          "data-packet RAW-DATA should be an (unsigned-byte 8) vector.")
      (is (= 64 (cl:length raw))
          "data-packet RAW-DATA size should be sample-count * element-size bytes."))))

(test high-level-autoload-healthcheck
  (let* ((status (daq:healthcheck nil))
         (loaded (getf status :status))
         (directory (getf status :resolved-native-directory))
         (autoload-error (getf status :autoload-error)))
    (is (eq :loaded loaded)
        "High-level smoke coverage should confirm the native library loads.")
    (is (stringp directory)
        "High-level smoke coverage should expose the discovered native library directory.")
    (is (null autoload-error)
        "High-level smoke coverage should confirm autoload completed without an error.")))
