#!/usr/bin/env python3

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

LOW_LEVEL_PACKAGE = "opendaq"


@dataclass(frozen=True)
class ReaderSpec:
    name: str
    low_level_name: str


@dataclass(frozen=True)
class MethodSpec:
    name: str
    low_level_name: str
    wraps_result_as: str | None = None


@dataclass(frozen=True)
class ClassSpec:
    name: str
    initargs: tuple[str, ...]
    constructor: str
    readers: tuple[ReaderSpec, ...]
    methods: tuple[MethodSpec, ...]


RATIO_SLICE = (
    ClassSpec(
        name="ratio",
        initargs=("numerator", "denominator"),
        constructor="ratio/create-ratio",
        readers=(
            ReaderSpec(name="numerator", low_level_name="ratio/get-numerator"),
            ReaderSpec(name="denominator", low_level_name="ratio/get-denominator"),
        ),
        methods=(
            MethodSpec(name="simplify", low_level_name="ratio/simplify", wraps_result_as="ratio"),
        ),
    ),
)


def emit_class_definition(spec: ClassSpec) -> list[str]:
    lines = [f"(defclass {spec.name} (managed-object)", "  ("]
    lines.extend(
        [
            f"   (%{initarg}-initarg :initarg :{initarg} :initform nil)"
            for initarg in spec.initargs
        ]
    )
    lines.extend(["   ))", "", ""])
    return lines


def emit_initializer(spec: ClassSpec) -> list[str]:
    initarg_checks = " ".join(f"{name}-p" for name in spec.initargs)
    initarg_call = " ".join(spec.initargs)
    initarg_error = " and ".join(f":{name.upper()}" for name in spec.initargs)

    lines = [
        f"(defmethod initialize-instance :after ((object {spec.name})",
        "                                       &key (pointer nil pointer-p)",
    ]
    lines.extend(
        [
            f"                                            ({initarg} nil {initarg}-p)"
            for initarg in spec.initargs
        ]
    )
    lines.extend(
        [
            "                                       &allow-other-keys)",
            "  (cond",
            "    (pointer-p",
            f"      (when (or {initarg_checks})",
            f"        (error \"{spec.name.upper()} cannot be initialized with both :POINTER and constructor arguments.\"))",
            "      (%adopt-pointer object pointer))",
            f"    ((and {initarg_checks})",
            f"      (%adopt-pointer object ({LOW_LEVEL_PACKAGE}:{spec.constructor} {initarg_call})))",
            "    (t",
            f"      (error \"{spec.name.upper()} requires either :POINTER or {initarg_error}.\"))))",
            "",
        ]
    )
    return lines


def emit_wrapper_constructor(spec: ClassSpec) -> list[str]:
    return [
        f"(defun wrap-{spec.name} (pointer)",
        f"  (make-instance '{spec.name} :pointer pointer))",
        "",
    ]


def emit_readers(spec: ClassSpec) -> list[str]:
    lines: list[str] = []
    for reader in spec.readers:
        lines.extend(
            [
                f"(defgeneric {reader.name} (object))",
                f"(defmethod {reader.name} ((object {spec.name}))",
                f"  ({LOW_LEVEL_PACKAGE}:{reader.low_level_name} (%require-live-pointer object)))",
                "",
            ]
        )
    return lines


def emit_methods(spec: ClassSpec) -> list[str]:
    lines: list[str] = []
    for method in spec.methods:
        lines.append(f"(defgeneric {method.name} (object))")
        lines.append(f"(defmethod {method.name} ((object {spec.name}))")
        low_level_call = f"({LOW_LEVEL_PACKAGE}:{method.low_level_name} (%require-live-pointer object))"
        if method.wraps_result_as is None:
            lines.append(f"  {low_level_call})")
        else:
            lines.append(f"  (wrap-{method.wraps_result_as} {low_level_call}))")
        lines.append("")
    return lines


def render_output() -> str:
    lines = [
        ";;; This file is autogenerated by tools/generate_high_level_bindings.py.",
        ";;; Do not edit it manually.",
        "",
        "(in-package #:opendaq.high-level)",
        "",
    ]

    for spec in RATIO_SLICE:
        lines.extend(emit_class_definition(spec))
        lines.extend(emit_initializer(spec))
        lines.extend(emit_wrapper_constructor(spec))
        lines.extend(emit_readers(spec))
        lines.extend(emit_methods(spec))

    lines.extend(
        [
            "(export '(release",
            "         raw-pointer",
            "         ratio",
            "         wrap-ratio",
            "         numerator",
            "         denominator",
            "         simplify))",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the high-level Common Lisp bindings layer."
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Path to the generated high-level Lisp file.",
    )
    parser.add_argument(
        "--include-dir",
        type=Path,
        default=None,
        help="Reserved for future schema-driven generation.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_output(), encoding="utf-8")


if __name__ == "__main__":
    main()
